import json
from pythonnet import load
import json
import sys, random
import os
load("coreclr")
import clr
sys.path.append(os.path.join(os.getcwd(), "netstandard2.0"))
clr.AddReference("UAssetAPI")
from UAssetAPI import UAsset
from UAssetAPI.UnrealTypes import EngineVersion

important_items = {
            "ITEM_IMPORTANT_ADVENTURERS_MAP", "ITEM_IMPORTANT_BLACK_PEPPER", "ITEM_IMPORTANT_BLUE_METAL",
            "ITEM_IMPORTANT_BLUE_ORB", "ITEM_IMPORTANT_BOATMANS_BONE", "ITEM_IMPORTANT_BOTTOMLESS_POT",
            "ITEM_IMPORTANT_BROKEN_SWORD", "ITEM_IMPORTANT_CONTINENT_MAP", "ITEM_IMPORTANT_DREAMSTONE",
            "ITEM_IMPORTANT_ECHO_FLUTE", "ITEM_IMPORTANT_FAERIE_FLUTE", "ITEM_IMPORTANT_FAERIE_MAP",
            "ITEM_IMPORTANT_GOLDEN_MEDAL", "ITEM_IMPORTANT_GREEN_ORB", "ITEM_IMPORTANT_HAMMER_OF_GAIA",
            "ITEM_IMPORTANT_LOVERS_LOCKET", "ITEM_IMPORTANT_MAGIC_KEY", "ITEM_IMPORTANT_MOD_ROD",
            "ITEM_IMPORTANT_ORICHALCUM", "ITEM_IMPORTANT_PURPLE_ORB", "ITEM_IMPORTANT_RAINBOW_DROP",
            "ITEM_IMPORTANT_RAS_MIRROR", "ITEM_IMPORTANT_RED_ORB", "ITEM_IMPORTANT_ROYAL_MISSIVE",
            "ITEM_IMPORTANT_SILVER_ORB", "ITEM_IMPORTANT_SUNSTONE", "ITEM_IMPORTANT_THIEFS_KEY",
            "ITEM_IMPORTANT_ULTIMATE_KEY", "ITEM_IMPORTANT_VERY_NAUGHTY_BOOK", "ITEM_IMPORTANT_WAKEY_DUST",
            "ITEM_IMPORTANT_WORDS_OF_WISDOM", "ITEM_IMPORTANT_WRECKING_BALL", "ITEM_IMPORTANT_YELLOW_ORB"
        }
item_names = ["ITEM_EQUIP_WEAPON_COPPER_SWORD","ITEM_EQUIP_WEAPON_STEEL_BROADSWORD","ITEM_EQUIP_WEAPON_OROCHIS_SWORD","ITEM_EQUIP_WEAPON_ZOMBIESBANE","ITEM_EQUIP_WEAPON_MOUNTAINCLEAVER","ITEM_EQUIP_WEAPON_THUNDERBOLT_BLADE","ITEM_EQUIP_WEAPON_SIREN_SWORD","ITEM_EQUIP_WEAPON_SWORD_OF_RUIN","ITEM_EQUIP_WEAPON_BLIZZARD_BLADE","ITEM_EQUIP_WEAPON_FALCON_BLADE","ITEM_EQUIP_WEAPON_BASTARD_SWORD","ITEM_EQUIP_WEAPON_STORMLORDS_SWORD","ITEM_EQUIP_WEAPON_DOUBLE-EDGED_SWORD","ITEM_EQUIP_WEAPON_SWORD_OF_KINGS","ITEM_EQUIP_WEAPON_RUBISSS_SWORD","ITEM_EQUIP_WEAPON_IRON_AXE","ITEM_EQUIP_WEAPON_BATTLEAXE","ITEM_EQUIP_WEAPON_HEADSMANS_AXE","ITEM_EQUIP_WEAPON_CONQUERORS_AXE","ITEM_EQUIP_WEAPON_CYPRESS_STICK","ITEM_EQUIP_WEAPON_OAKEN_CLUB","ITEM_EQUIP_WEAPON_SLAPSTICK","ITEM_EQUIP_WEAPON_SLEDGEHAMMER","ITEM_EQUIP_WEAPON_WAR_HAMMER","ITEM_EQUIP_WEAPON_WIZARDS_STAFF","ITEM_EQUIP_WEAPON_SNOOZE_STICK","ITEM_EQUIP_WEAPON_STAFF_OF_ANTIMAGIC","ITEM_EQUIP_WEAPON_RUNE_STAFF","ITEM_EQUIP_WEAPON_STAFF_OF_SENTENCING","ITEM_EQUIP_WEAPON_SOMATIC_STAFF","ITEM_EQUIP_WEAPON_STAFF_OF_RESURRECTION","ITEM_EQUIP_WEAPON_STAFF_OF_STRIFE","ITEM_EQUIP_WEAPON_LIGHTNING_STAFF","ITEM_EQUIP_WEAPON_STAFF_OF_RAIN","ITEM_EQUIP_WEAPON_SAGES_STAFF","ITEM_EQUIP_WEAPON_GODBIRD_SCEPTRE","ITEM_EQUIP_WEAPON_AURORA_STAFF","ITEM_EQUIP_WEAPON_IRON_CLAWS","ITEM_EQUIP_WEAPON_GOLDEN_CLAWS","ITEM_EQUIP_WEAPON_KNUCKLEDUSTERS","ITEM_EQUIP_WEAPON_FIRE_CLAWS","ITEM_EQUIP_WEAPON_DRAGONSBANE","ITEM_EQUIP_WEAPON_DRAGON_CLAWS","ITEM_EQUIP_WEAPON_BEAST_CLAWS","ITEM_EQUIP_WEAPON_ORICHALCUM_CLAWS","ITEM_EQUIP_WEAPON_BRONZE_KNIFE","ITEM_EQUIP_WEAPON_DIVINE_DAGGER","ITEM_EQUIP_WEAPON_POISON_NEEDLE","ITEM_EQUIP_WEAPON_ASSASSINS_DAGGER","ITEM_EQUIP_WEAPON_BOOMERANG","ITEM_EQUIP_WEAPON_EDGED_BOOMERANG","ITEM_EQUIP_WEAPON_GUSTERANG","ITEM_EQUIP_WEAPON_SWALLOWTAIL","ITEM_EQUIP_WEAPON_FLAMETANG_BOOMERANG","ITEM_EQUIP_WEAPON_METAL_WING_BOOMERANG","ITEM_EQUIP_WEAPON_HUNTERS_MOON","ITEM_EQUIP_WEAPON_CHAIN_SICKLE","ITEM_EQUIP_WEAPON_THORN_WHIP","ITEM_EQUIP_WEAPON_CHAIN_WHIP_ITEMS","ITEM_EQUIP_WEAPON_BEASTLY_BULLWHIP","ITEM_EQUIP_WEAPON_SPIKED_STEEL_WHIP","ITEM_EQUIP_WEAPON_MORNING_STAR","ITEM_EQUIP_WEAPON_DRAGONTAIL_WHIP","ITEM_EQUIP_WEAPON_SCOURGE_WHIP","ITEM_EQUIP_WEAPON_EMPRESSS_WHIP","ITEM_EQUIP_WEAPON_GRINGHAM_WHIP","ITEM_EQUIP_WEAPON_DESTRUCTIBALL","ITEM_EQUIP_WEAPON_IRON_LANCE","ITEM_EQUIP_WEAPON_HOLY_LANCE","ITEM_EQUIP_WEAPON_BATTLE_FORK","ITEM_EQUIP_WEAPON_SANDSTORM_SPEAR","ITEM_EQUIP_WEAPON_DEMON_SPEAR","ITEM_EQUIP_WEAPON_GODLY_POKER","ITEM_EQUIP_WEAPON_ASTRAEAS_ABACUS","ITEM_EQUIP_WEAPON_ABRACADABRACUS","ITEM_EQUIP_WEAPON_SIZEABLE_SCISSORS","ITEM_EQUIP_SHIELD_POT_LID","ITEM_EQUIP_SHIELD_LEATHER_SHIELD","ITEM_EQUIP_SHIELD_SCALE_SHIELD","ITEM_EQUIP_SHIELD_BRONZE_SHIELD","ITEM_EQUIP_SHIELD_SILVER_PLATTER","ITEM_EQUIP_SHIELD_IRON_SHIELD","ITEM_EQUIP_SHIELD_LIGHT_SHIELD","ITEM_EQUIP_SHIELD_ICE_SHIELD","ITEM_EQUIP_SHIELD_MAGIC_SHIELD","ITEM_EQUIP_SHIELD_DRAGON_SHIELD","ITEM_EQUIP_SHIELD_TEMPEST_SHIELD","ITEM_EQUIP_SHIELD_FLAME_SHIELD","ITEM_EQUIP_SHIELD_SILVER_SHIELD","ITEM_EQUIP_SHIELD_MIRROR_SHIELD","ITEM_EQUIP_SHIELD_POWER_SHIELD","ITEM_EQUIP_SHIELD_HEROS_SHIELD","ITEM_EQUIP_SHIELD_SHIELD_OF_SHAME","ITEM_EQUIP_SHIELD_OGRE_SHIELD","ITEM_EQUIP_SHIELD_GODDESS_SHIELD","ITEM_EQUIP_HELMET_LEATHER_HAT","ITEM_EQUIP_HELMET_TURBAN","ITEM_EQUIP_HELMET_FEATHERED_CAP","ITEM_EQUIP_HELMET_HARDWOOD_HEADWEAR","ITEM_EQUIP_HELMET_KINGS_CROWN","ITEM_EQUIP_HELMET_FUR_HOOD","ITEM_EQUIP_HELMET_SCHOLARS_CAP","ITEM_EQUIP_HELMET_POINTY_HAT","ITEM_EQUIP_HELMET_IRON_HELMET","ITEM_EQUIP_HELMET_BLACK_BANDANA","ITEM_EQUIP_HELMET_HERMES_HAT","ITEM_EQUIP_HELMET_TOP_HAT","ITEM_EQUIP_HELMET_SILVER_TIARA","ITEM_EQUIP_HELMET_ORTEGAS_HELM","ITEM_EQUIP_HELMET_MASK_OF_IMPLACABILITY","ITEM_EQUIP_HELMET_PHANTOM_MASK","ITEM_EQUIP_HELMET_THIEFS_TURBAN","ITEM_EQUIP_HELMET_IRON_MASK","ITEM_EQUIP_HELMET_MAD_CAP","ITEM_EQUIP_HELMET_BUNNY_EARS","ITEM_EQUIP_HELMET_RAGING_BULL_HELM","ITEM_EQUIP_HELMET_MYTHRIL_HELM","ITEM_EQUIP_HELMET_HAPLESS_HELM","ITEM_EQUIP_HELMET_THINKING_CAP","ITEM_EQUIP_HELMET_GREAT_HELM","ITEM_EQUIP_HELMET_LIGHT_HELM","ITEM_EQUIP_HELMET_STAR_CIRCLET","ITEM_EQUIP_HELMET_DUPLIC_HAT","ITEM_EQUIP_HELMET_HEAVENLY_HELM","ITEM_EQUIP_ARMOR_PLAIN_CLOTHES","ITEM_EQUIP_ARMOR_WAYFARERS_CLOTHES","ITEM_EQUIP_ARMOR_LEATHER_ARMOUR","ITEM_EQUIP_ARMOR_TRAINING_TOGS","ITEM_EQUIP_ARMOR_TORTOISE_SHELL","ITEM_EQUIP_ARMOR_LEATHER_DRESS","ITEM_EQUIP_ARMOR_SHELL_ARMOUR","ITEM_EQUIP_ARMOR_LEATHER_CAPE","ITEM_EQUIP_ARMOR_IRON_APRON","ITEM_EQUIP_ARMOR_BOXER_SHORTS","ITEM_EQUIP_ARMOR_CHAIN_MAIL","ITEM_EQUIP_ARMOR_SPARRING_SUIT","ITEM_EQUIP_ARMOR_CLOAK_OF_EVASION","ITEM_EQUIP_ARMOR_LEATHER_KILT","ITEM_EQUIP_ARMOR_MAGICAL_SKIRT","ITEM_EQUIP_ARMOR_BLACK_PYJAMAS","ITEM_EQUIP_ARMOR_IRON_ARMOUR","ITEM_EQUIP_ARMOR_SILK_ROBE","ITEM_EQUIP_ARMOR_FULL_PLATE_ARMOUR","ITEM_EQUIP_ARMOR_FUR_VEST","ITEM_EQUIP_ARMOR_FIZZLE_RETARDANT_SUIT","ITEM_EQUIP_ARMOR_MAGICAL_ROBES","ITEM_EQUIP_ARMOR_MAGIC_ARMOUR","ITEM_EQUIP_ARMOR_PARTY_DRESS","ITEM_EQUIP_ARMOR_SMART_SUIT","ITEM_EQUIP_ARMOR_GARISH_GARB","ITEM_EQUIP_ARMOR_AGILITY_GILET","ITEM_EQUIP_ARMOR_EARTHENWEAR","ITEM_EQUIP_ARMOR_WIZARDS_ROBE","ITEM_EQUIP_ARMOR_SILVER_CUIRASS","ITEM_EQUIP_ARMOR_CAT_SUIT","ITEM_EQUIP_ARMOR_EPIC_APRON","ITEM_EQUIP_ARMOR_ANGELS_ROBE","ITEM_EQUIP_ARMOR_STEALTH_SUIT","ITEM_EQUIP_ARMOR_SPIKED_ARMOUR","ITEM_EQUIP_ARMOR_DRAGON_MAIL","ITEM_EQUIP_ARMOR_INFERNAL_ARMOUR","ITEM_EQUIP_ARMOR_SCANDALOUS_SWIMSUIT","ITEM_EQUIP_ARMOR_FLOWING_DRESS","ITEM_EQUIP_ARMOR_DRAGON_DOJO_DUDS","ITEM_EQUIP_ARMOR_FLAME_ARMOUR","ITEM_EQUIP_ARMOR_BANDIT_MAIL","ITEM_EQUIP_ARMOR_AURORAL_ARMOUR","ITEM_EQUIP_ARMOR_MAGIC_BIKINI","ITEM_EQUIP_ARMOR_DRAGON_ROBE","ITEM_EQUIP_ARMOR_SHIMMERING_DRESS","ITEM_EQUIP_ARMOR_BLESSED_BIKINI","ITEM_EQUIP_ARMOR_DARK_ROBE","ITEM_EQUIP_ARMOR_GLOMBOLERO","ITEM_EQUIP_ARMOR_CORSAIRS_COAT","ITEM_EQUIP_ARMOR_YGGDRASIL_DRESS_COAT","ITEM_EQUIP_ARMOR_GODBIRD_ROBE","ITEM_EQUIP_ARMOR_EXOTOGA","ITEM_EQUIP_ARMOR_GODBIRD_ARMOUR","ITEM_EQUIP_ACCESSORY_STRENGTH_RING","ITEM_EQUIP_ACCESSORY_TOUGH_GUY_TATTOO","ITEM_EQUIP_ACCESSORY_MIGHTY_ARMLET","ITEM_EQUIP_ACCESSORY_GARTER","ITEM_EQUIP_ACCESSORY_DOH_HICAN","ITEM_EQUIP_ACCESSORY_GOLD_ROSARY","ITEM_EQUIP_ACCESSORY_LEG_WARMERS","ITEM_EQUIP_ACCESSORY_TEN_TON_TOUPEE","ITEM_EQUIP_ACCESSORY_COWER_RING","ITEM_EQUIP_ACCESSORY_SKULL_RING","ITEM_EQUIP_ACCESSORY_AGILITY_RING","ITEM_EQUIP_ACCESSORY_MERCURYS_BANDANA","ITEM_EQUIP_ACCESSORY_METEORITE_BRACER","ITEM_EQUIP_ACCESSORY_GOLD_CHAIN","ITEM_EQUIP_ACCESSORY_RESTLESS_HEART","ITEM_EQUIP_ACCESSORY_TITAN_BELT","ITEM_EQUIP_ACCESSORY_RECOVERY_RING","ITEM_EQUIP_ACCESSORY_SCHOLARS_SPECS","ITEM_EQUIP_ACCESSORY_CARE_RING","ITEM_EQUIP_ACCESSORY_GODDESS_RING","ITEM_EQUIP_ACCESSORY_BUNNY_TAIL","ITEM_EQUIP_ACCESSORY_GOLDEN_TIARA","ITEM_EQUIP_ACCESSORY_HENS_TOOTH","ITEM_EQUIP_ACCESSORY_SACRED_AMULET","ITEM_EQUIP_ACCESSORY_ELEVATING_SHOES","ITEM_EQUIP_ACCESSORY_PACIFIER","ITEM_EQUIP_ACCESSORY_SLIME_EARRINGS","ITEM_EQUIP_ACCESSORY_RUBY_WRISTBAND","ITEM_USE_ITEM_MEDICAL_HERB","ITEM_USE_ITEM_STRONG_MEDICINE","ITEM_USE_ITEM_SPECIAL_MEDICINE","ITEM_USE_ITEM_SAGES_STONE","ITEM_USE_ITEM_MAGIC_WATER","ITEM_USE_ITEM_SAGES_ELIXIR","ITEM_USE_ITEM_ELFIN_ELIXIR","ITEM_USE_ITEM_PRAYER_RING","ITEM_USE_ITEM_ANTIDOTAL_HERB","ITEM_USE_ITEM_MOONWORT_BULB","ITEM_USE_ITEM_SKYBELL","ITEM_USE_ITEM_DEDAZZLE_GRASS","ITEM_USE_ITEM_WHISPERING_NECTAR","ITEM_USE_ITEM_YGGDRASIL_LEAF","ITEM_USE_ITEM_HOLY_WATER","ITEM_USE_ITEM_TANGLEWEB","ITEM_USE_ITEM_COAGULANT","ITEM_USE_ITEM_OOMPH_POWDER","ITEM_USE_ITEM_CHIMERA_WING","ITEM_USE_ITEM_DIEAMEND","ITEM_USE_ITEM_SEED_OF_STRENGTH","ITEM_USE_ITEM_SEED_OF_PROTECTION","ITEM_USE_ITEM_SEED_OF_RESILIENCE","ITEM_USE_ITEM_SEED_OF_WISDOM","ITEM_USE_ITEM_SEED_OF_AGILITY","ITEM_USE_ITEM_SEED_OF_LUCK","ITEM_USE_ITEM_SEED_OF_LIFE","ITEM_USE_ITEM_SEED_OF_MAGIC","ITEM_USE_ITEM_FAIL_IS_A_FOUR_LETTER_WORD","ITEM_USE_ITEM_THE_SADDEST_STORY_EVER_TOLD","ITEM_USE_ITEM_TEARS_BEFORE_BEDTIME","ITEM_USE_ITEM_LOVING_LIVING_A_GRINNERS_GUIDE","ITEM_USE_ITEM_COMEDY_BOOK","ITEM_USE_ITEM_DIARY_OF_A_HARDMAN","ITEM_USE_ITEM_THE_GIRLS_OWN_ANNUAL","ITEM_USE_ITEM_CHEATER_BOOK","ITEM_USE_ITEM_BENICE_BOOK","ITEM_USE_ITEM_LEAP_BEFORE_YOU_LOOK","ITEM_USE_ITEM_SMART_BOOK","ITEM_USE_ITEM_PRIMMS_PRIMER","ITEM_USE_ITEM_THE_CHAMPIONS_CODE","ITEM_USE_ITEM_NAUGHTY_BOOK","ITEM_USE_ITEM_SPHERE_OF_LIGHT","ITEM_USE_ITEM_FADING_JENNY","ITEM_USE_ITEM_LYRE_OF_IRE","ITEM_USE_ITEM_POUCH_OF_MUSK","ITEM_USE_ITEM_NIGHT_LIGHT","ITEM_USE_ITEM_WAR_DRUM","ITEM_IMPORTANT_WORDS_OF_WISDOM","ITEM_IMPORTANT_ADVENTURERS_MAP","ITEM_IMPORTANT_FAERIE_MAP","ITEM_IMPORTANT_WRECKING_BALL","ITEM_IMPORTANT_DREAMSTONE","ITEM_IMPORTANT_WAKEY_DUST","ITEM_IMPORTANT_ROYAL_MISSIVE","ITEM_IMPORTANT_BLACK_PEPPER","ITEM_IMPORTANT_RAS_MIRROR","ITEM_IMPORTANT_MOD_ROD","ITEM_IMPORTANT_BOATMANS_BONE","ITEM_IMPORTANT_LOVERS_LOCKET","ITEM_IMPORTANT_BOTTOMLESS_POT","ITEM_IMPORTANT_THIEFS_KEY","ITEM_IMPORTANT_MAGIC_KEY","ITEM_IMPORTANT_ULTIMATE_KEY","ITEM_IMPORTANT_ECHO_FLUTE","ITEM_IMPORTANT_RED_ORB","ITEM_IMPORTANT_GREEN_ORB","ITEM_IMPORTANT_PURPLE_ORB","ITEM_IMPORTANT_BLUE_ORB","ITEM_IMPORTANT_SILVER_ORB","ITEM_IMPORTANT_YELLOW_ORB","ITEM_IMPORTANT_FAERIE_FLUTE","ITEM_IMPORTANT_SUNSTONE","ITEM_IMPORTANT_RAINBOW_DROP","ITEM_IMPORTANT_ORICHALCUM","ITEM_IMPORTANT_VERY_NAUGHTY_BOOK","ITEM_IMPORTANT_BROKEN_SWORD","ITEM_IMPORTANT_HAMMER_OF_GAIA","ITEM_IMPORTANT_BLUE_METAL","ITEM_IMPORTANT_GOLDEN_MEDAL","ITEM_EQUIP_ACCESSORY_DRAGON_SCALES","ITEM_EQUIP_ACCESSORY_AMULET_BELL","ITEM_EQUIP_ACCESSORY_HOLY_SYMBOL_OF_AMULET","ITEM_EQUIP_ACCESSORY_FAIRY_BANGLE","ITEM_EQUIP_ACCESSORY_POISON_RESISTANCE_NECKLACE","ITEM_EQUIP_ACCESSORY_SEALING_RESISTANCE_NECKLACE","ITEM_EQUIP_ACCESSORY_PHANTOM_RESISTANCE_NECKLACE","ITEM_EQUIP_ACCESSORY_ALARM_RING","ITEM_EQUIP_ACCESSORY_MANGETSU_RING","ITEM_EQUIP_ACCESSORY_RING_OF_REASON","ITEM_EQUIP_ACCESSORY_FLAME_EARRINGS","ITEM_EQUIP_ACCESSORY_ICE_EARRINGS","ITEM_EQUIP_ACCESSORY_WIND_EARRINGS","ITEM_IMPORTANT_CONTINENT_MAP"]

def create_json():

    uasset_folder = "./uasset/"  
    json_folder = "./jsonfile/"

    if not os.path.exists(json_folder):
        os.makedirs(json_folder)

    
    for file_name in os.listdir(uasset_folder):
        if file_name.endswith(".uasset"):  
            uasset_path = os.path.join(uasset_folder, file_name)  
            json_path = os.path.join(json_folder, f"{os.path.splitext(file_name)[0]}.json")  
            try:
                
                my_asset = UAsset(uasset_path, EngineVersion.VER_UE4_27)
                json_data = my_asset.SerializeJson()
                
                with open(json_path, "w", encoding="utf-8") as json_file:
                    json_file.write(json_data)
                
                print(f"Fichier JSON créé : {json_path}")
            except Exception as e:
                print(f"Erreur lors du traitement de {file_name}: {e}")


def create_uasset():
    uasset_folder = "./uasset/"  
    json_folder = "./jsonfile/"  

    if not os.path.exists(json_folder):
        os.makedirs(json_folder)

    for file_name in os.listdir(json_folder):
        if file_name.endswith(".json"):  
            json_path  = os.path.join(json_folder, file_name)  
            uasset_path = os.path.join(uasset_folder, f"{os.path.splitext(file_name)[0]}.uasset")  
            
            try:
                with open(json_path, "r", encoding="utf-8") as f:
                    myAsset = UAsset.DeserializeJson(f.read())

                myAsset.Write(uasset_path)
                
                print(f"Fichier UASSET créé : {uasset_path}")
            except Exception as e:
                print(f"Erreur lors du traitement de {uasset_path}: {e}")


def items_or_golds_or_empty(pourcentage_items, pourcentage_golds, pourcentage_empty):
   
    if pourcentage_items + pourcentage_golds + pourcentage_empty != 100:
        raise ValueError("Error % is not equal to 100%.")

    tirage = random.randint(1, 100)

    if tirage <= pourcentage_items:
        return "item"
    elif tirage <= pourcentage_items + pourcentage_golds:
        return "gold"
    else:
        return "empty"


# myAsset = UAsset("./uasset/GOP_Encounter_Monster.uasset", EngineVersion.VER_UE4_27)
# with open("./jsonfile/GOP_Encounter_Monster.json", "w", encoding="utf-8") as f:
#     f.write(myAsset.SerializeJson())
